environment:
  node_pre_gyp_accessKeyId:
    secure: J0Bhc089DjlB2VE7Y4SiR5yex1cYeYscC6sXc5+wUMg=
  node_pre_gyp_secretAccessKey:
    secure: RJGlxPP+hUt/pVbY4vBUWW21uGInC8pbyiQ6wz+8cS20k3cQtpnxs9HNFUI4KfBS
  matrix:
    - nodejs_version: 8
      platform: x64
    - nodejs_version: 9
      platform: x64
    - nodejs_version: 10
      platform: x64


os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF 